In [2]:
import pandas as pd
from sklearn.model_selection import KFold #This is for the K-Fold Cross Validation
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

In [3]:
data=pd.read_csv("Boston.CSV")
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
x=data.iloc[:,:12].values
y=data.iloc[:,12].values

In [5]:
print(x)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [6]:
print(y)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

# Creating K-Fold Corss Validation object with 5 folds. You can use any number of folds

In [7]:
kf=KFold(n_splits=5,shuffle=True)
kf

KFold(n_splits=5, random_state=None, shuffle=True)

In [8]:
model=LinearRegression()
model

LinearRegression()

# Split function is used to separet the training and testing data in each fold

In [9]:
kf.split(data) #This returns the indexes of training & testing data for each fold

<generator object _BaseKFold.split at 0x000001AFB3549DD0>

In [10]:
list(kf.split(data))

[(array([  0,   2,   3,   6,   7,   8,   9,  10,  11,  12,  15,  16,  17,
          19,  20,  21,  22,  23,  24,  26,  27,  28,  29,  30,  31,  32,
          33,  34,  35,  36,  37,  38,  40,  44,  45,  46,  47,  49,  51,
          52,  53,  54,  56,  57,  58,  59,  60,  61,  63,  64,  67,  70,
          72,  73,  74,  75,  76,  77,  78,  80,  81,  83,  84,  85,  86,
          88,  89,  90,  92,  93,  94,  96,  97,  98, 100, 102, 103, 104,
         105, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
         119, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 133, 134,
         135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 146, 148, 149,
         150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
         163, 164, 165, 166, 168, 169, 171, 173, 174, 175, 176, 178, 179,
         180, 181, 182, 184, 185, 187, 188, 189, 190, 192, 194, 195, 196,
         197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 208, 209, 212,
         213, 214, 215, 216, 217, 218,

# Training the model with training set and validating with testing set in each fold and appending RSquared Value & MSE for each fold

In [11]:
MSEL=[]
RSL=[]

In [12]:
for i in list(kf.split(data)):
    model.fit(x[i[0],:],y[i[0]])
    RSL.append(model.score(x[i[0],:],y[i[0]]))
    y_pred=model.predict(x[i[1],:])
    MSEL.append(np.sqrt(mean_squared_error(y_pred,y[i[1]])))

# R-Squared value with Cross Validation

In [13]:
np.mean(RSL)*100

73.78350529364167

# Mean Squared Error with Cross Validation

In [14]:
np.mean(MSEL)

4.877961892099927